---
# defaults file for base

# Global config
# User to configure (ssh keys for exemple)
# base_user:
# Upgrade all packages when running the role
base_package_upgrade: false

# SSH key config
# Add SSH Key to authorized_keys
# Path of the SSH Key on the Ansible server
# base_ssh_key_path:

# Pi config
# Raspberry PI wireless configuration (with rfkill)
# The remote server should be in an Ansible group named 'pi'
# State could be : blocked or unblocked
base_pi_rf_device_state:
  # Wifi
  wlan: blocked
  # Bluetooh
  bluetooth: blocked

# Pi fan config
# The remote server should be in an Ansible group named 'pi'
# Exemple circuit : https://raspberrypi.stackexchange.com/a/105820
base_pi_fan:
  # Enable or disable the fan control
  enabled: false
  # GPIO pin number to control the fan
  gpio_pin: 18
  # Temperature in celsius to enable the fan
  enable_temp: 50
  # Temperature in celsius to disable the fan
  disable_temp: 40
