---
# tasks file for pihole

- name: "Main | Configure system requirements"
  ansible.builtin.import_tasks: requirements.yml

- name: "Main | Ensure piHole is installed"
  ansible.builtin.import_tasks: install.yml

- name: "Main | Ensure piHole is up to date"
  ansible.builtin.import_tasks: upgrade.yml

- name: "Main | Ensure piHole configuration"
  ansible.builtin.import_tasks: config/main.yml
